# select * from REST_REVIEW order by REST_ID desc
# SELECT A.REST_ID,A.REST_NAME,A.FOOD_TYPE,A.FAVORITES,A.ADDRESS,round(AVG(B.REVIEW_SCORE),2) SCORE 
# from REST_INFO A
# cross join REST_REVIEW B
# on A.REST_ID = B.REST_ID

SELECT A.REST_ID,A.REST_NAME,A.FOOD_TYPE,A.FAVORITES,A.ADDRESS,round(AVG(B.REVIEW_SCORE),2) SCORE 
FROM REST_INFO A, REST_REVIEW B
where A.REST_ID = B.REST_ID AND A.ADDRESS LIKE '서울%'
GROUP BY REST_ID
order by SCORE DESC, A.FAVORITES DESC